name: "HANA HDI Container Management"
description: "Manages HANA HDI containers by cleaning up old instances and setting up new ones"
inputs:
  instance-prefix:
    description: "Prefix for service instance names"
    required: true
  service-plan-id:
    description: "HANA service plan ID" 
    required: true
  auth-url:
    description: "OAuth authentication URL"
    required: true
  service-manager-url:
    description: "Service Manager URL"
    required: true
  cleanup-age-hours:
    description: "Age threshold in hours for cleanup"
    required: false
    default: "1"
  config-path:
    description: "Path where to write configuration files"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Cleanup old instances
      run: node ${{ github.action_path }}/../../scripts/hana-hdi-container/cleanup.js
      shell: bash
      env:
        INPUT_AUTH_URL: ${{ inputs.auth-url }}
        INPUT_SERVICE_MANAGER_URL: ${{ inputs.service-manager-url }}
        INPUT_CLEANUP_AGE_HOURS: ${{ inputs.cleanup-age-hours }}
        INPUT_INSTANCE_PREFIX: ${{ inputs.instance-prefix }}
    - name: Setup new instance
      run: node ${{ github.action_path }}/../../scripts/hana-hdi-container/setup.js
      shell: bash
      env:
        INPUT_AUTH_URL: ${{ inputs.auth-url }}
        INPUT_SERVICE_MANAGER_URL: ${{ inputs.service-manager-url }}
        INPUT_INSTANCE_PREFIX: ${{ inputs.instance-prefix }}
        INPUT_SERVICE_PLAN_ID: ${{ inputs.service-plan-id }}
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
