name: Enforce Changelog

# usage in your project
# + create file enforce-changelog.yml in .github/workflows
# + add the following content to enforce-changelog.yml

# name: Enforce Changelog
# on:
#  pull_request:
#    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
# jobs:
#   enforce-changelog:
#     uses: cap-js/.github/.github/workflows/enforce-changelog.yml@main
#     secrets: inherit
#     permissions:
#       pull-requests: write



on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: cap-js/.github
          ref: add/simplerChLogTest # must be changed to main before merging
          # ref: main
          path: ./cap-js-github

      - name: Enforce Changelog
        uses: actions/github-script@v7
        with:
          script: |
            const run = require('./cap-js-github/.github/scripts/enforce-changelog.js');
            await run({ context, core, github });
