# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
  workflow_call:
    inputs:
      dry-run:
        description: Dry run
        required: false
        type: boolean
        default: false
      tag:
        description: The tag to use during publish, values are latest, next
        required: false
        type: string
        default: latest

permissions:
  contents: write

env:
  INPUTS_DRY_RUN: ${{ inputs.dry-run }}
  INPUTS_TAG: ${{ inputs.tag }}
  DRY_RUN_OPTION: ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}


jobs:
  check-versions:
    runs-on: ubuntu-latest
    outputs:
      do-release: ${{ steps.check-versions.outputs.do-release }}
    steps:
      - run: |
          echo "INPUTS_DRY_RUN: $INPUTS_DRY_RUN"